# Generated by Django 4.1.7 on 2023-02-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_alter_task_task_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_desc',
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('WRK', 'WORK'), ('SCH', 'SCHOOL'), ('PSL', 'PERSONAL')], default='PSL', max_length=3),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_title',
            field=models.CharField(max_length=120),
        ),
    ]
