# Generated by Django 4.1.7 on 2023-02-23 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=255)),
                ('is_pc', models.BooleanField(default=False)),
                ('is_mobile', models.BooleanField(default=False)),
                ('is_xbox', models.BooleanField(default=False)),
                ('is_ps4', models.BooleanField(default=False)),
                ('is_switch', models.BooleanField(default=False)),
                ('game_publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.publisher')),
            ],
        ),
    ]
