# Generated by Django 4.1.7 on 2023-02-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_publisher',
            field=models.CharField(max_length=60),
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
