# Generated by Django 4.1.7 on 2023-02-23 05:10

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_game_publisher_delete_publisher'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='game',
            managers=[
                ('game_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
