# Generated by Django 4.1.7 on 2023-02-23 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='game',
            managers=[
            ],
        ),
    ]
